[custom]
ruleset=🗂️ OneDrive,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/OneDrive.list
ruleset=💻 Microsoft,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Microsoft.list
ruleset=🍎 Apple,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Apple.list
ruleset=📲 Telegram,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Telegram.list
ruleset=📲 Discord,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Discord.list
ruleset=📲 Line,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Line.list
ruleset=📲 Line TV,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/LineTV.list
ruleset=🪙 Crypto,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/Crypto.list
ruleset=🤖 OpenAI,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/OpenAi.list
ruleset=🤡 IPApi,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/IPApi.list
ruleset=💰 Paypal,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/PayPal.list
ruleset=🛒 Amazon,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Amazon.list
ruleset=🌐 Google,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Google.list
ruleset=📹 Porn,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Porn.list
ruleset=📹 Tiktok,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/TikTok.list
ruleset=📹 DAZN,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/DAZN.list
ruleset=📹 HBO,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/HBO.list
ruleset=📹 Hulu,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Hulu.list
ruleset=📹 DisneyPlus,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/DisneyPlus.list
ruleset=📹 YouTube,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/YouTube.list
ruleset=📹 Twitch,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Twitch.list
ruleset=🎥 Netflix,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Netflix.list
ruleset=🧩 Github,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Github.list
ruleset=🧩 JetBrains,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/JetBrains.list
ruleset=🦜 Twitter,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Twitter.list
ruleset=🎮 Steam,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Steam.list
ruleset=🎮 SteamCN,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/SteamCN.list
ruleset=🎮 Xbox,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Xbox.list
ruleset=🎮 Blizzard,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Blizzard.list
ruleset=🤡 CustomAsshole,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/CustomAsshole.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/UnBan.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/GoogleCN.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaIp.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Download.list
ruleset=🇰🇵 国内网络,[]GEOIP,CN
ruleset=🌎 其他网站,[]FINAL
custom_proxy_group=🚀 Auto`select`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]IEPL`[]DIRECT
custom_proxy_group=🧜‍♂️ 手动选择`select`.*
custom_proxy_group=♻️ AutoAll`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇵 国内网络`select`[]DIRECT`[]🚀 Auto`[]♻️ AutoAll`[]🧜‍♂️ 手动选择
custom_proxy_group=🗂️ OneDrive`select`[]DIRECT`[]🚀 Auto`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择
custom_proxy_group=💻 Microsoft`select`[]DIRECT`[]🚀 Auto`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🚀 Auto`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择
custom_proxy_group=📲 Telegram`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📲 Discord`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📲 Line`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📲 Line TV`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🪙 Crypto`select`[]🇯🇵 日本节点`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🤖 OpenAI`select`[]🇯🇵 日本节点`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🤡 IPApi`select`[]🇯🇵 日本节点`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=💰 Paypal`select`[]🇺🇲 美国节点`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🛒 Amazon`select`[]🇺🇲 美国节点`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🌐 Google`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 Porn`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 Tiktok`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 DAZN`select`[]🇺🇲 美国节点`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 HBO`select`[]🇺🇲 美国节点`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 Hulu`select`[]🇺🇲 美国节点`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 DisneyPlus`select`[]🇺🇲 美国节点`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 Twitch`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🎥 Netflix`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🧩 Github`select`[]IEPL`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🧩 JetBrains`select`[]🇨🇳 台湾节点`[]IEPL`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🦜 Twitter`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🎮 Steam`select`[]🚀 Auto`[]DIRECT`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择
custom_proxy_group=🎮 SteamCN`select`[]DIRECT`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择
custom_proxy_group=🎮 Xbox`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🎮 Blizzard`select`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🤡 CustomAsshole`select`[]🇯🇵 日本节点`[]🚀 Auto`[]♻️ AutoAll`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🌎 其他网站`select`[]🚀 Auto`[]♻️ AutoAll`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🧜‍♂️ 手动选择
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(新|新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=IEPL`url-test`(IEPL|Bos)`http://www.gstatic.com/generate_204`300,,50
enable_rule_generator=true
overwrite_original_rules=true
