[custom]
ruleset=🗂️ OneDrive,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/OneDrive.list
ruleset=💻 Microsoft,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Microsoft.list
ruleset=🍎 Apple,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Apple.list
ruleset=📲 Telegram,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Telegram.list
ruleset=📲 Discord,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Discord.list
ruleset=📲 Line,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Line.list
ruleset=📲 Line TV,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/LineTV.list
ruleset=🪙 Crypto,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/Crypto.list
ruleset=🤖 OpenAI,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/OpenAi.list
ruleset=🤖 Claude,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Claude.list
ruleset=🤖 Gemini,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Gemini.list
ruleset=💰 Paypal,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/PayPal.list
ruleset=🛒 Amazon,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Amazon.list
ruleset=📹 YouTube,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/YouTube.list
ruleset=🌐 Google,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Google.list
ruleset=📹 Porn,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Porn.list
ruleset=📹 Pikpak,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/Pikpak.yaml
ruleset=📹 Tiktok,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/tiktok.list
ruleset=📹 DAZN,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/DAZN.list
ruleset=📹 HBO,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/HBO.list
ruleset=📹 Hulu,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Hulu.list
ruleset=📹 DisneyPlus,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/DisneyPlus.list
ruleset=📹 Twitch,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Twitch.list
ruleset=🎥 Netflix,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Netflix.list
ruleset=🎥 Deezer,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Deezer.list
ruleset=🧩 Github,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/github.list
ruleset=🧩 JetBrains,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/JetBrains.list
ruleset=🦜 Twitter,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Twitter.list
ruleset=🎮 Steam,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Steam.list
ruleset=🎮 SteamCN,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/SteamCN.list
ruleset=🎮 Xbox,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Xbox.list
ruleset=🤡 IPApi,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/IPApi.list
ruleset=🤡 CustomAsshole,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/CustomAsshole.list
ruleset=🤡 CNService,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/oray.list
ruleset=🤡 TWService,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/tw.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/UnBan.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/GoogleCN.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaIp.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list
ruleset=🇰🇵 国内网络,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Download.list
ruleset=🇰🇵 国内网络,[]GEOIP,CN
ruleset=🌎 其他网站,[]FINAL
custom_proxy_group=🚀 Auto`select`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]LB_HK`[]LB_JP`[]LB_USA`[]LB_SG`[]LB_KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🧜‍♂️ 手动选择`select`.*
custom_proxy_group=♻️ AutoAll`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇵 国内网络`select`[]DIRECT`[]🚀 Auto`[]♻️ AutoAll`[]🧜‍♂️ 手动选择
custom_proxy_group=🗂️ OneDrive`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=💻 Microsoft`select`[]DIRECT`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择
custom_proxy_group=📲 Telegram`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📲 Discord`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📲 Line`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📲 Line TV`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🪙 Crypto`select`[]JP`[]🚀 Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🤖 OpenAI`select`[]JP`[]🚀 Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🤖 Claude`select`[]JP`[]🚀 Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🤖 Gemini`select`[]JP`[]🚀 Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 Tiktok`select`[]JP`[]🚀 Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=💰 Paypal`select`[]USA`[]🚀 Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🛒 Amazon`select`[]USA`[]🚀 Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 DAZN`select`[]USA`[]🚀 Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 HBO`select`[]USA`[]🚀 Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 Hulu`select`[]USA`[]🚀 Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 DisneyPlus`select`[]USA`[]🚀 Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🌐 Google`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 Porn`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 Pikpak`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=📹 Twitch`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🎥 Netflix`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🎥 Deezer`select`[]🚀 Auto`[]SG`[]HK`[]MO`[]JP`[]USA`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🧩 Github`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🧩 JetBrains`select`[]TW`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🦜 Twitter`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🎮 Steam`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🎮 SteamCN`select`[]DIRECT`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择
custom_proxy_group=🎮 Xbox`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🤡 IPApi`select`[]JP`[]🚀 Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🤡 CustomAsshole`select`[]JP`[]🚀 Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🤡 CNService`select`[]DIRECT`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择
custom_proxy_group=🤡 TWService`select`[]TW`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=🌎 其他网站`select`[]🚀 Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]TAG_HK`[]TAG_MO`[]TAG_JP`[]TAG_SG`[]TAG_USA`[]TAG_TW`[]♻️ AutoAll`[]🧜‍♂️ 手动选择`[]DIRECT
custom_proxy_group=HK`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=MO`url-test`(澳门|澳|Macau)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=JP`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=USA`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=SG`url-test`(新|新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=TW`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=KR`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=LB_HK`load-balance`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=LB_JP`load-balance`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=LB_USA`load-balance`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=LB_SG`load-balance`(新|新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=LB_TW`load-balance`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=LB_KR`load-balance`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=TAG_HK`url-test`(香港)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=TAG_MO`url-test`(澳门)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=TAG_JP`url-test`(日本)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=TAG_SG`url-test`(新加坡)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=TAG_USA`url-test`(美国)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=TAG_TW`url-test`(台湾)`http://www.gstatic.com/generate_204`300,5,50
enable_rule_generator=true
overwrite_original_rules=true
