[custom]

;规则
ruleset=🛸 Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🛸 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=🛸 AI,https://raw.githubusercontent.com/bk1d/oc_config/refs/heads/main/AI.list
ruleset=🛸 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🛸 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=🛸 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Copilot/Copilot.list
ruleset=🛸 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list
ruleset=🛸 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Civitai/Civitai.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
ruleset=🍎 AppleAPNs,https://raw.githubusercontent.com/bk1d/oc_config/refs/heads/main/AppleAPNs.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list
ruleset=🎵 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Spotify/Spotify.list
ruleset=📹 Youtube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
ruleset=📹 Youtube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTubeMusic/YouTubeMusic.list
ruleset=📹 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=🐦 Twitter,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Twitter/Twitter.list
ruleset=🌻 Oray,https://raw.githubusercontent.com/bk1d/oc_config/refs/heads/main/oray.list
ruleset=🤡 Abandon,https://raw.githubusercontent.com/bk1d/oc_config/refs/heads/main/Custom.list
ru

; ruleset=🎯 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Lan/Lan.list
ruleset=🎯 直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Download.list
ruleset=🎯 直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Download/Download.list

;ruleset=🎯 直连,[]GEOIP,LAN
ruleset=🎯 直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

;分组规则
custom_proxy_group=🚀 Auto`select`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT
custom_proxy_group=🔧 手动指定`select`.*
custom_proxy_group=♻️ Auto All`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎯 直连`select`[]DIRECT`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All
custom_proxy_group=🛸 Microsoft`select`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT
custom_proxy_group=🛸 Google`select`[]🇼🇸 Taiwan`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT
custom_proxy_group=🛸 Github`select`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT
custom_proxy_group=🛸 AI`select`[]🇼🇸 Taiwan`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All
custom_proxy_group=🍎 AppleAPNs`select`[]🚀 Auto`[]DIRECT`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All
custom_proxy_group=📲 Telegram`select`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT
custom_proxy_group=🎵 Spotify`select`[]🇭🇰 Hong Kong`[]🚀 Auto`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT
custom_proxy_group=📹 Youtube`select`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT
custom_proxy_group=🎮 Steam`select`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT
custom_proxy_group=🎮 Steam CN`select`[]DIRECT`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All
custom_proxy_group=🐦 Twitter`select`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT
custom_proxy_group=🌻 Oray`select`[]DIRECT`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All
custom_proxy_group=🤡 Abandon`select`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇼🇸 Taiwan`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🇼🇸 Taiwan`[]🚀 Auto`[]🇭🇰 Hong Kong`[]🇯🇵 Japan`[]🇸🇬 Singapore`[]🇺🇸 USA`[]🔧 手动指定`[]🏴‍☠️ Self-hosted`[]♻️ Auto All`[]DIRECT

; 节点组
custom_proxy_group=🇭🇰 Hong Kong`url-test`(Hong Kong|HongKong|hongkong|香港)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇼🇸 Taiwan`url-test`(Taiwan|台湾)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 Japan`url-test`(Japan|日本)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 Singapore`url-test`(Singapore|新加坡)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇸 USA`url-test`(United States|USA|美国)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🏴‍☠️ Self-hosted`url-test`(DMIT|Self)`http://www.gstatic.com/generate_204`300,,200

; 其他
enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

clash_rule_base=https://raw.githubusercontent.com/bk1d/oc_config/refs/heads/main/clash_rule_base_v5.yml


;luck
